FROM ubuntu:22.04


ARG MINIO_ENDPOINT
ARG MINIO_ACCESS_KEY
ARG MINIO_SECRET_KEY

ENV MINIO_ENDPOINT $MINIO_ENDPOINT
ENV MINIO_ACCESS_KEY $MINIO_ACCESS_KEY
ENV MINIO_SECRET_KEY $MINIO_SECRET_KEY

RUN apt-get update && apt-get install -y curl mysql-client

# Install mc from Minio's GitHub release
RUN curl -o /usr/local/bin/mc https://dl.min.io/client/mc/release/linux-amd64/mc && \
    chmod +x /usr/local/bin/mc

# Copy the repository files to the container
COPY . /app

RUN chmod +x /app/minio.sh

ENTRYPOINT ["/app/minio.sh"]
