FROM alpine:3.14

ENV AWS_ACCOUNT_ID=""
ENV AWS_ACCESS_KEY_ID=""
ENV AWS_SECRET_ACCESS_KEY=""
ENV AWS_DEFAULT_REGION="eu-west-2"
ENV AWS_PROFILE="default"

ARG AWS_ACCOUNT_ID=""
ARG AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ARG AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
ARG AWS_PROFILE=$AWS_PROFILE

#apk update
RUN apk add bash
RUN apk add aws-cli
RUN apk add jq
RUN apk add docker
RUN apk add curl

#	RUN apk add git
#	RUN apk add terraform
#	RUN apk add openssh-client
#	RUN apk add openssh-keygen

RUN mkdir ~/.aws

#	Do not need it if we pass env vars
#	RUN echo "[default]" >> ~/.aws/credentials
#	RUN echo "output=json" >> ~/.aws/credentials

RUN echo "[default]" >> ~/.aws/config
RUN echo "region=$AWS_DEFAULT_REGION" >> ~/.aws/config
RUN echo "output=json" >> ~/.aws/config

RUN cat ~/.aws/config

WORKDIR /
COPY / /

RUN curl -LO https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl
RUN chmod +x kubectl
RUN mv kubectl /usr/local/bin/

ENTRYPOINT ["bash", "kickstart_aws_ecr_cred_sync.sh"]
