name: Conditional WorkFlow Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ feature/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo code
        uses: actions/checkout@v2 
        with:
          ref: "main"
      if: github.repository == 'octo-org/octo-repo-prod'
      - name: Run ls
        run: ls -la

