name: Every hour ECR Creds Sync Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ feature/* ]
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:
    inputs:
      task_name:
        type: choice
        description: 'Please choose the job'
        default: 'ecr-creds-sync'
        required: true
        options:
          - 'ecr-creds-sync'

env:
  aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
  aws_access_key_id: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  aws_secret_access_key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  aws_region: ${{ vars.AWS_REGION }}
  task_name : ${{ github.event.inputs.task_name }}

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out this repo code
      uses: actions/checkout@v2
      with:
        ref: "main"

    - name: AWS ECR repository creds sync
      run: chmod +x ./aws_cli_ecr_creds_sync.sh && ./aws_cli_ecr_creds_sync.sh "${{ env.aws_account_id }}" "${{ env.aws_access_key_id }}" "${{ env.aws_secret_access_key }}" "${{ env.aws_region }}"
