name: Multistage Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ feature/* ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo code
        uses: actions/checkout@v2 
        with:
          ref: "main"

  stageone:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Run pwd
        run: pwd
  
  stagetwo:
    runs-on: ubuntu-latest
    needs: [stageone]
    steps:
      - name: Run ls
        run: ls -la

