name: opsapi unit test suite

on:
  push:
    branches: [ dummy ]
  pull_request:
    branches: [ feature/* ]
  schedule:
    - cron: "0 0 * * *" #Need to run everyday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo code
        uses: actions/checkout@v2 
        with:
          ref: "main"

      - name: build and run the opsapi docker image unit tests
        run: chmod +x ./opsapi_test_suite.sh && ./opsapi_test_suite.sh

