name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify package.json exists
        run: ls -la

      - name: Install dependencies
        run: npm install
        working-directory: ./cypress

      - name: Run Cypress Tests
        id: cypress
        working-directory: ./cypress
        run: |
          npx cypress run || echo "cypress_failed=true" >> $GITHUB_ENV

      - name: 'Upload screenshots and videos to Slack'
        uses: trymbill/cypress-slack-video-upload-action@v1.3.0
        with:
            token: ${{ secrets.SLACK_TOKEN }}
            channels: 'cypress-test-results'
            workdir: cypress/cypress
            message-text: 'Cypress Test Passed!'
            
      - name: 'Upload screenshots and videos to Slack'
        uses: trymbill/cypress-slack-video-upload-action@v1.3.0
        if: failure()
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channels: 'engineering-ops'
          message-text: 'Cypress tests failed! They have been placed in this thread, good luck.'

      