name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify package.json exists
        run: ls -la

      - name: Install dependencies
        run: npm install
        working-directory: ./cypress

      - name: Run Cypress Tests
        id: cypress
        working-directory: ./cypress
        run: |
          npx cypress run || echo "cypress_failed=true" >> $GITHUB_ENV

      - name: Upload Cypress Screenshots
        if: failure() || env.cypress_failed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/cypress/screenshots

      - name: Upload Cypress Videos
        if: failure() || env.cypress_failed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/cypress/videos

      - name: Send Success Notification to Slack
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "channel": "#cypress-test-results",
            "text": "✅ *Cypress Tests Passed!* :rocket: \n Repository: ${{ github.repository }}",
            "username": "Cypress Bot",
            "icon_emoji": ":white_check_mark:"
          }' $SLACK_WEBHOOK_URL

      - name: Send Failure Notification to Slack
        if: failure() || env.cypress_failed == 'true'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          FILES=$(find cypress/screenshots cypress/videos -type f | head -3)  # Limit to 3 files
          for FILE in $FILES; do
            curl -F file=@$FILE -F "initial_comment=❌ Cypress Test Failure: See attached file." -F channels=#cypress-test-results -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" https://slack.com/api/files.upload
          done