name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify package.json exists
        run: ls -la

      - name: Install dependencies
        run: npm install
        working-directory: ./cypress

      - name: Run Cypress Tests
        id: cypress
        working-directory: ./cypress
        run: |
          npx cypress run || echo "cypress_failed=true" >> $GITHUB_ENV

      - name: 'Upload screenshots and videos to Slack'
        uses: trymbill/cypress-slack-video-upload-action@v1.3.0
        with:
            token: ${{ secrets.SLACK_TOKEN }}
            channels: 'cypress-test-results'
            workdir: cypress/cypress

      - name: Slack Notification for Whitefalcon Admin UI Smoke Login Test 
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_CHANNEL: cypress-test-results
            SLACK_COLOR: ${{ job.status }}
            SLACK_ICON: https://github.com/rtCamp.png?size=48
            SLACK_MESSAGE: 'Smoketest Login Test using Cypress ${{ env.TARGET_ENV }} env :rocket:'
            SLACK_TITLE: Smoketest Admin UI Smoke Login Test on ${{ env.TARGET_ENV }}
            SLACK_USERNAME: rtCamp
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}