name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome

      - name: 'Upload screenshots and videos to Slack'
        uses: trymbill/cypress-slack-video-upload-action@v1.3.0
        with:
            token: ${{ secrets.SLACK_TOKEN }}
            channels: 'cypress-test-results'
            workdir: cypress/cypress

      - name: Slack Notification for Whitefalcon Admin UI Smoke Login Test 
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_CHANNEL: general
            SLACK_COLOR: ${{ job.status }}
            SLACK_ICON: https://github.com/rtCamp.png?size=48
            SLACK_MESSAGE: 'Smoketest Login Test using Cypress ${{ env.TARGET_ENV }} env :rocket:'
            SLACK_TITLE: Smoketest Admin UI Smoke Login Test on ${{ env.TARGET_ENV }}
            SLACK_USERNAME: rtCamp
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}