name: Test sub action variables

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    outputs:
      IMAGE_REF: ${{ steps.set_image.outputs.IMAGE_REF }}

    steps:
      - uses: actions/checkout@v4

      - name: Call sub action
        uses: ./.github/actions/print-vars
        with:
          app_name: my-sample-app
          api_key: ${{ secrets.MY_API_KEY }}

      - name: Set IMAGE_REF output
        id: set_image
        run: |
          echo "IMAGE_REF=nginx" >> "$GITHUB_OUTPUT"
  test1:
    needs: test
    runs-on: ubuntu-latest
    name: Test 1 job print env var from Test

    steps:
      - name: Print IMAGE_REF from Test job
        run: |
          echo "${{ needs.test.outputs.IMAGE_REF }}"
